import {
  deleteFramework,
  deleteRelation,
  getGraphViewState,
  listArticles,
  listCandidates,
  listFrameworks,
  listInteractionEvents,
  listKnowledgePoints,
  listRelations,
  listRelationAnalysisJobs,
  listRelationFeedbackPatterns,
  recordInteraction,
  saveCandidate,
  saveCandidates,
  saveFramework,
  saveGraphViewState,
  saveRelation,
  saveRelations,
  saveRelationAnalysisJob,
  saveRelationFeedbackPattern,
} from './database'

export const knowledgeRepository = {
  listArticles,
  listKnowledgePoints,
  listFrameworks,
  listRelations,
  listRelationAnalysisJobs,
  listRelationFeedbackPatterns,
  listCandidates,
  listInteractionEvents,
  getGraphViewState,
  saveFramework,
  deleteFramework,
  saveRelation,
  saveRelations,
  saveRelationAnalysisJob,
  saveRelationFeedbackPattern,
  deleteRelation,
  saveCandidate,
  saveCandidates,
  recordInteraction,
  saveGraphViewState,
}